### ISSUE TITLE
Error: rhel-6-server-thirdparty-oracle-java-rpms is not a valid repository ID...

### ISSUE THREAD

**Issue by z3cka** [UCLALibrary/ansible_uclalib_role_java#3]
`...Use --list option to see valid repositories.`

I get this on first run of a modification of the `uclalib_solr4test.yml` file in the  [ansible_uclalib_plays](https://github.com/UCLALibrary/ansible_uclalib_plays) repo.

**playbook yaml**:

``` yaml

---
- name: uclalib_solr4local_rhel.yml
  # sudo: true
  hosts: local_rhel
  # Define the intended solr applicaitons in the vars section below
  # Optionally define the solr instance type and master host fqdn
  vars:
    iptables_allowed_input_rules:
      - src_ip: 0.0.0.0/16
        dest_port: 80
        protocol: tcp
    tomcat_applications:
      - app_name: solr
        shut_port: 8006
        conn_port: 8081
        rproxy_path: solr
    solr_xms: 4096m
    solr_xmx: 4096m
    solr_cores:
      - ident: www-local-rhel
        type: 'drupal'
# Use 1 for master and 2 for slave
    solr_instance_type: 1
# Uncomment variable below when solr_instance_type is 2 enter correct FQDN for solr master
#    solr_master_host: t-w-solrmaster01.library.ucla.edu

  roles:
    - { role: ansible_uclalib_role_java }
    - { role: ansible_uclalib_role_apache }
    - { role: ansible_uclalib_role_tomcat }
    - { role: ansible_uclalib_role_solr4 }
    - { role: ansible_uclalib_role_iptables }
```

My target is a Red Hat 6.7 box with a developer license enabled.
What other info would be helpful?
